### ISSUE TITLE
Output file in APSIM simulations

### ISSUE THREAD

**Issue by femiguez** [isuforesite/M1Analysis#1]
The output files in APSIM produce a line that says 'precision = 5' is there any meaning to this. I did not expect this. Is it a by product of how the .apsim files are generated?

**Comment by mnowatzke** [comment]
Yes, it is a byproduct of the Python wrapper. I can change or remove it easily enough if it is a problem.

**Comment by femiguez** [comment]
I don't think you need to remove it, but just wondering why it was there and if there is any meaning to it.
